server:
  port: 8880

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/zhu?useUnicode=true
  rabbitmq:
    addresses: 192.168.199.200:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        concurrency: 5
        acknowledge-mode: manual
        max-concurrency: 10
        prefetch: 1
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true



mybatis:
  check-config-location: true
  type-aliases-package: com.zou.huzhu2entity.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**.xml

logging:
  level:
    com.zou: debug